plugins:
  discourse_user_fancy_titles_enabled:
    default: true
    client: true
  title_position:
    client: true
    type: enum
    default: "default"
    choices:
      - "default"
      - "after_username"
      - "below_username"
